"""empty message

Revision ID: c3c5b2a3890f
Revises: f8247b92ebb1
Create Date: 2020-02-03 17:21:20.486508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3c5b2a3890f'
down_revision = 'f8247b92ebb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('train_num_no')
    op.drop_table('station_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_list',
    sa.Column('station_num', mysql.VARCHAR(length=4), nullable=False),
    sa.Column('station_name', mysql.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('station_num'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('train_num_no',
    sa.Column('train_num', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('train_route', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('no', mysql.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('train_num'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
