"""empty message

Revision ID: f8247b92ebb1
Revises: 
Create Date: 2020-01-18 23:54:24.612466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8247b92ebb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_type', sa.String(length=4), nullable=True),
    sa.Column('train_num', sa.String(length=16), nullable=False),
    sa.Column('station_depart', sa.String(length=64), nullable=True),
    sa.Column('station_arrive', sa.String(length=64), nullable=True),
    sa.Column('station_schedule', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id', 'train_num'),
    sa.UniqueConstraint('train_num')
    )
    op.create_table('train_time_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_num', sa.String(length=16), nullable=True),
    sa.Column('serial_num', sa.Integer(), nullable=True),
    sa.Column('station_name', sa.String(length=64), nullable=True),
    sa.Column('time_arrive', sa.Time(), nullable=True),
    sa.Column('time_depart', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['train_num'], ['train_line.train_num'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('train_time_table')
    op.drop_table('train_line')
    # ### end Alembic commands ###
